# -*- coding: utf-8 -*-
"""FlaskApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wxMz_LpPL5gPTPgIviQjYhlnNwESXPWJ
"""

import numpy as np
import pickle
import pandas as pd
from flask import Flask, request
from flask import Flask, request, jsonify, render_template

app=Flask(__name__)
pickle_in = open("Fishclassifier.pkl","rb")
classifier=pickle.load(pickle_in)

@app.route('/')
#def hello():
#    return "This is a APP Creation Test"
def home():
    return render_template('index.html')

@app.route('/predict',methods=['POST'])
def predict():
    '''
    For rendering results on HTML GUI
    '''
    int_features = [x for x in request.form.values()]
    final_features = [np.array(int_features)]
    prediction = classifier.predict(final_features)

    
    return render_template('index.html', prediction_text='The Fish belong to species {}'.format(prediction))

#@app.route('/predict')
#def predict_class():
#    Weight=request.args.get('Weight')
#    Length1=request.args.get('Length1')
#    Length2=request.args.get('Length2')
#    Length3=request.args.get('Length3')
#    Height=request.args.get('Height')
#    Width=request.args.get('Width')
    
#    prediction=classifier.predict([[Weight,Length1,Length2,Length3,Height,Width]])
#    return " The Predicated Class is"+ str(prediction)

if __name__=='__main__':
    app.run()

